version: "3.9"

services:
  djangoapp:
    build: .
    command: >
      sh -c "
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=db
    depends_on:
      - db
    volumes:
      - .:/code

  db:
    container_name: db
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./database/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf

  adminer:
    image: adminer
    restart: always
    ports:
      - "8282:8080"
    depends_on:
      - db

volumes:
  postgres_data:
