version: '3.9'

services:
  djangoapp:
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=django_db
      - DB_PORT=3306
      - DB_HOST=db
    depends_on:
      - db
    volumes:
      - .:/code
    networks:
      - app-network

  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=django_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8282:8080"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network:
    driver: bridge
