name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: django_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd mysqladmin ping --silent
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: mysql://root:password@localhost:3306/django_db

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker-compose build
        docker-compose push

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd app
        coverage run -m pytest
        coverage report -m
        coverage html -d ./tests/reports/
      env:
        TESTING: 1

    - name: Upload test coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage-reports
        path: app/tests/reports/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 62.72.16.216 >> ~/.ssh/known_hosts

    - name: Check directory contents
      run: ls -R

    - name: Install Ansible
      run: sudo apt-get install -y ansible

    - name: Deploy with Ansible
      run: ansible-playbook -i ansible/hosts.ini ansible/deploy.yml
